### ISSUE TITLE
Scroll amount not being updated and scroll y position issues

### ISSUE THREAD

**Issue by canadianeagle** [fcisio/gatsby-locomotivescroll-starter#4]
Hey fcisio,
First, thanks so much for making this starter - couldn't get anything else to work until this.

I'm facing an issue - well two issues.
1. Whenever I scroll down, change the state of something in my app, or do something like change the width of the window to test responsiveness, locomotive scroll jumps to the top / resets it's scroll position to 0. Not sure why, but I haven't been able to diagnose it.
2. I'm trying to store the page scroll y amount in state. But whenever I use the on scroll function, and assign the y variable to state in this function, the scroll doesn't work. Console.log works in here to see the y variable though, and this is strange to me. See the example below:

`useEffect(() => {
    let locomotiveScroll = window.scroll;

    locomotiveScroll.on("scroll", func => {
      setScrollY(func.scroll.y); //this causes jumping/lag/breaks the scroll so I can't scroll)
      console.log("y", func.scroll.y); //this works without any issues
    })
  })`

I'd appreciate any pointers. Thanks so much :)

**Comment by fcisio** [comment]
Hey, this is the expected behavior.
Browsers can retain the position of the native scroll, but Locomotive Scroll is not native.

It's essentially an animation of a container div.

There's currently a [Pull Request](https://github.com/locomotivemtl/locomotive-scroll/pull/212) on the project repo addressing this and proposing a workaround.

You should try enabling Gatsby's [Fast Refresh](https://github.com/gatsbyjs/gatsby/discussions/28390), I have a feeling it should fix your issue. Feature released on `2.28.0`

> What react-refresh does is a step further. If you are someone who builds client-side rendered applications and pass around a lot of state management in tools such as react context, redux, apollo, or really any react hooks, changes to your code no longer do a complete page refresh! 

[Reference](https://medium.com/javascript-in-plain-english/what-is-react-fast-refresh-f3d1e8401333#:~:text=React%20Fast%20Refresh%20is%20a,to%20make%20it%20platform%20independent.)

**Comment by canadianeagle** [comment]
@fcisio thanks so much for the quick response. I enabled fast refresh - I'm loving it so far. Unfortunately doesn't resolve my issue.
That's a good way of explaining it - an animated div ;) - I guess the scroll position reset is an issue I can ignore for now.

Particularly #2, any ideas on any other way to actively track the y position from inside the [locomotiveScroll.on("scroll", ...] or anywhere else even? 
 
To elaborate, I'm trying to add effects like rotating an element, or adjusting the opacity based on how much the scroll.y position is.

**Comment by fcisio** [comment]
You could either, print a value in a CSS Variable from inside the `scroll` function.

But, ScrollTrigger is most likely what you are looking for. [Here is a tutorial](https://www.youtube.com/watch?v=JnLn8Rq4p_I&ab_channel=snorklTV) on how to make it work with Locomotive Scroll

**Comment by canadianeagle** [comment]
You my friend are a legend - thanks for the ideas and direction. I'll probably use both strategies as they'll come in handy for different use cases. Thanks again + God bless!
